SOLVE_DIFF = "solve"
EXIT = "exit"

EULER_METHOD = "EULER"
RUNGE_THIRD_METHOD = "RUNGE_3"
RUNGE_FOURTH_METHOD = "RUNGE_4"

DIFF_EQUATION_TYPE_ONE = "1"
DIFF_EQUATION_TYPE_TWO = "2"
DIFF_EQUATION_TYPE_THREE = "3"
DIFF_EQUATION_TYPE_FOUR = "4"
